In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer

In [2]:
cancer = load_breast_cancer()

In [3]:
df = pd.DataFrame(cancer['data'],columns=cancer['feature_names'])

In [4]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
scaler = StandardScaler()

In [7]:
scaled_data = scaler.fit_transform(df)

In [8]:
ssdf = pd.DataFrame(scaled_data,columns=cancer['feature_names'])

In [9]:
ssdf.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0     1.097064     -2.073335        1.269934   0.984375         1.568466   
1     1.829821     -0.353632        1.685955   1.908708        -0.826962   
2     1.579888      0.456187        1.566503   1.558884         0.942210   
3    -0.768909      0.253732       -0.592687  -0.764464         3.283553   
4     1.750297     -1.151816        1.776573   1.826229         0.280372   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0          3.283515        2.652874             2.532475       2.217515   
1         -0.487072       -0.023846             0.548144       0.001392   
2          1.052926        1.363478             2.037231       0.939685   
3          3.402909        1.915897             1.451707       2.867383   
4          0.539340        1.371011             1.428493      -0.009560   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                2.255747  ...      1.886690      -1.359293         2.303601   
1               -0.868652  ...      1.805927      -0.369203         1.535126   
2               -0.398008  ...      1.511870      -0.023974         1.347475   
3                4.910919  ...     -0.281464       0.133984        -0.249939   
4               -0.562450  ...      1.298575      -1.466770         1.338539   

   worst area  worst smoothness  worst compactness  worst concavity  \
0    2.001237          1.307686           2.616665         2.109526   
1    1.890489         -0.375612          -0.430444        -0.146749   
2    1.456285          0.527407           1.082932         0.854974   
3   -0.550021          3.394275           3.893397         1.989588   
4    1.220724          0.220556          -0.313395         0.613179   

   worst concave points  worst symmetry  worst fractal dimension  
0              2.296076        2.750622                 1.937015  
1              1.087084       -0.243890                 0.281190  
2              1.955000        1.152255                 0.201391  
3              2.175786        6.046041                 4.935010  
4              0.729259       -0.868353                -0.397100  

[5 rows x 30 columns]

In [11]:
bb = pd.DataFrame()
bb['mean radius'] = ssdf['mean radius'].round(decimals=5)
bb['mean texture'] = ssdf['mean texture'].round(decimals=5)

In [13]:
bb.head()

mean radius  mean texture
0      1.09706      -2.07334
1      1.82982      -0.35363
2      1.57989       0.45619
3     -0.76891       0.25373
4      1.75030      -1.15182

# Calculating Principle Components of given matrix(dataframe)

**First we need to take the covarience matrix of the dataframe or matrix**

In [14]:
#Here we have *bb* as our dataframe

In [15]:
cov = bb.cov()

In [16]:
cov

mean radius  mean texture
mean radius      1.001761      0.324352
mean texture     0.324352      1.001760

**And Eigen vector of the covarience matrix is Principe components of given matrix but for calculating eigen vectors we need eigen values**  

In [17]:
import scipy.linalg as la

In [18]:
evEV = la.eig(cov)

In [19]:
evEV[0] #--> Eigen Values

array([1.32611259+0.j, 0.67740885+0.j])

In [23]:
#Values Calculated by mathematical way

evEV[1] #--> Eigen Vectors(its a row structure(-> ->)
                                              #(-> ->))

array([[ 0.70710704, -0.70710653],
       [ 0.70710653,  0.70710704]])

In [24]:
#Values Calculated by using SKLEARN.PCA()

#array([[ 0.70710678,  0.70710678],
 #      [-0.70710678,  0.70710678]])(its a column structure(|  |)
  #                                                        (V  V)
   #                                                       (|  |)
    #                                                      (V  V)

   **PCA is used for dimensional reductionality because having more dimensions leads to overfitting of the ML model**